[tool.poetry]
name = "core"
version = "0.1.0"
description = ""
authors = ["Ning <a24701770@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
